name: environment
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - expat=2.6.2
  - libffi=3.4.4
  - openssl=3.0.14
  - pip=24.2
  - python=3.12.0
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.2
      - altair==5.4.0
      - astunparse==1.6.3
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - blinker==1.8.2
      - cachetools==5.5.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorlog==6.8.2
      - construct==2.10.70
      - contourpy==1.2.0
      - cycler==0.12.1
      - dm-tree==0.1.8
      - et-xmlfile==1.1.0
      - filelock==3.13.1
      - flatbuffers==24.3.25
      - fonttools==4.44.3
      - formats==0.1.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-pasta==0.2.0
      - greenlet==3.0.3
      - grpcio==1.62.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - h5py==3.10.0
      - idna==3.6
      - imageio==2.34.1
      - imbalanced-learn==0.12.0
      - imblearn==0.0
      - intel-openmp==2021.4.0
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - keras==3.5.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==16.0.6
      - mako==1.3.5
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - mendeleev==0.15.0
      - mkl==2021.4.0
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - namex==0.0.7
      - narwhals==1.5.2
      - networkx==3.3
      - numpy==1.26.2
      - opencv-python==4.9.0.80
      - openmm==8.1.1
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - optree==0.12.1
      - optuna==3.6.1
      - packaging==21.3
      - pandas==2.1.3
      - patsy==0.5.6
      - phik==0.12.4
      - pillow==10.1.0
      - protobuf==4.25.3
      - pyarrow==17.0.0
      - pydeck==0.9.1
      - pyfiglet==0.8.post1
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - pywavelets==1.6.0
      - pyyaml==6.0.1
      - rdkit==2023.9.6
      - referencing==0.35.1
      - requests==2.31.0
      - rich==13.7.0
      - rpds-py==0.20.0
      - scikeras==0.4.1
      - scikit-image==0.23.2
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.0
      - setuptools==69.2.0
      - skorch==1.0.0
      - smmap==5.0.1
      - soupsieve==2.5
      - sqlalchemy==2.0.29
      - statsmodels==0.14.1
      - streamlit==1.37.1
      - sympy==1.12
      - tabulate==0.9.0
      - tbb==2021.11.0
      - tenacity==8.5.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-intel==2.17.0
      - termcolor==2.4.0
      - threadpoolctl==3.2.0
      - tifffile==2024.5.3
      - toml==0.10.2
      - torch==2.3.1
      - torch-geometric==2.5.3
      - torchaudio==2.3.1
      - torchvision==0.18.1
      - tqdm==4.66.4
      - typing-extensions==4.10.0
      - tzdata==2023.3
      - urllib3==2.2.1
      - watchdog==4.0.2
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - xgboost==2.0.3
      - yarl==1.9.4
